services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - timescaledb
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  ingest:
    build:
      dockerfile: pronto.ingest.Dockerfile
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - timescaledb

  metrics-api:
    build:
      dockerfile: pronto.api.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - timescaledb

  dashboard:
    build:
      dockerfile: pronto.dashboard.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./dashboard:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - metrics-api

volumes:
  timescaledb_data:
  grafana_data:
  node_modules:
  redis_data:
