services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  playground:
    build:
      dockerfile: ingest.Dockerfile
    env_file:
      - .env
    depends_on:
      - timescaledb

volumes:
  timescaledb_data:
