services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - timescaledb
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  ingest:
    build:
      dockerfile: ingest.Dockerfile
    env_file:
      - .env
    depends_on:
      - timescaledb

  metrics-api:
    build:
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - timescaledb

volumes:
  timescaledb_data:
  grafana_data:
